language: node_js
node_js:
- '12'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: IPFrrGNAtNj8UJm/29mDetOmvitLCsgGSt4nVq9vSb+qY7iyi9P727VY/+qPIo795lfEi4I0K4JuuK64wdazEqn2p7ukgTvpF6YgGxMrVOfTLnj3448xgqtMzBUttlNiYnzP0LVStsGJBx23YF512A4rg0+vALo4e1eZM4pYgdvN6IfkyzQJNSoRyTaygn76Y7wOBFeia7lOeE+IANa9U6frgqtWPV6GGgnEZy+xW227+DTopRP9FlsPAHDoYIUa5MsgyTpbJXeqaeJlnxnlO2pQmcWNzdWoQ/sviV/XTmAexHX4U83zEl4UNWr1DvLy/6lJoKIV6eOVZzgsIOg32SLqe4E0d4AH7o0WkIfiyAtuR+lVNHavV8w12feyubrGPRxr4gitqfOMIXDL+SLjvmUAIhdSdt987c5XBn+HdjWyyLcmccVEPYoBSNqZAerhXcY5730iNZj+qxnW/mL5tIhhEhsAeIKk1EeJu8rW0JoV/ouooppRvTVpItYLKNZcGU5sCjpnLUJOeZCCDhznE8XK8ml+RhWl+7zQY6lVNqJHlM7Nai5DdsenCzCCKrn8pfV3vfiK6Sm2eAdhSnif5xEBmtIb8UOwQ28sjQCXq/BayvUKYCUCddWfE1c9vKMuKpYAnxs4y35V0s04ZK9PUS3jdTUY8he7f7rBbiHYxE0=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/pub-sub
  - provider: npm
    skip_cleanup: true
    email: code@lekschas.de
    api_key:
      secure: QejqqQwHT6Eveesh4qrAOvFO43R8aatbMTCzWNltkchueTNK67oPs/oVevVviDBERhELt77oyQ2KKBex6YCQvWEMCGqricPV+u0SN6S5kFEBMn+5lAoKRhZO5vK5c3TRNYVDB06TeF422SP109KK66lFvXa77bOvHu/hbnNQkoP974r/T5H1rs10QsS+N02u4pGvzVRJwpx0SM1aaffphDOdos4L1oIN85Q09tqzhwbx5zXSNz357yraKqALxPzto6B65VbqxCm94xXSP9mvS40NMwalLiSGw0IwTHZ4p+MQ50qeV+Zt3YFAPHo9xU6BdkV1BioPSLs9sKys2RIFLfSPd6qtPth6ep8DsYL2v07S3YZ51QYU3Vch9or3tyLRJsMTib/fJsmMyjc/Zaa9u5G5JPsK1G9b5KKbf41zG2GYUbwmillPqqy5GVOtUkD2tGlHhg4rEXSD07hGNOJ819Jg0BkJtf8ZN8PlukJeGs3VRhnSvbZaar1mj74hbyu2UqwUkDvziY8Jwcy+7HTwYT0FUUrS8afJcxGB+SmUjmkt4P/7ZSddKDprFIyLA14GMfU8QPqAHLDiMuV+F1Amsfqpb9rzKoiQE7pKGHQtlSWNlJ6fkD6nHUSWCTQaouXuWbdf5WeoejWg0x8XB0Qm1Ro0NX6kcG279WhbB7xJwaY=
    on:
      branch: master
      tags: true
      repo: flekschas/pub-sub
